/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dynamicrepor.Jframe;

import com.mycompany.dynamicrepor.NormalSutunRaporlamaJava;
import com.mycompany.dynamicrepor.NormalSutunRaporlamaSql;
import com.mycompany.dynamicrepor.PastaDilimi;
import com.mycompany.dynamicrepor.UlkeListe;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lenovo
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAktör = new javax.swing.JMenu();
        jMenuItemAktor1 = new javax.swing.JMenuItem();
        jMenuItemAktor2 = new javax.swing.JMenuItem();
        jMenuFilm = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jMenuAktör.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/raporresim.png"))); // NOI18N
        jMenuAktör.setText("KlasikRapor");

        jMenuItemAktor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resactor.png"))); // NOI18N
        jMenuItemAktor1.setText("Aktörler");
        jMenuItemAktor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAktor1ActionPerformed(evt);
            }
        });
        jMenuAktör.add(jMenuItemAktor1);

        jMenuItemAktor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer.png"))); // NOI18N
        jMenuItemAktor2.setText("Musteriler");
        jMenuItemAktor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAktor2ActionPerformed(evt);
            }
        });
        jMenuAktör.add(jMenuItemAktor2);

        jMenuBar1.add(jMenuAktör);

        jMenuFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grafik.png"))); // NOI18N
        jMenuFilm.setText("GrafikselRapor");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_money-dollar-currency_2013249.png"))); // NOI18N
        jMenuItem3.setText("FilmSatışDağılım");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuFilm.add(jMenuItem3);

        jMenuBar1.add(jMenuFilm);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/barchart.png"))); // NOI18N
        jMenu2.setText("BarRaporlama");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_pen_stroke_sketch_doodle_lineart_212_451494.png"))); // NOI18N
        jMenuItem4.setText("MusteriUlkeSehir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAktor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAktor1ActionPerformed
      new NormalSutunRaporlamaJava();
    }//GEN-LAST:event_jMenuItemAktor1ActionPerformed

    private void jMenuItemAktor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAktor2ActionPerformed
        try {
            new NormalSutunRaporlamaSql();
        } catch (SQLException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemAktor2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            new PastaDilimi();
        } catch (SQLException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new UlkeListe();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAktör;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFilm;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAktor1;
    private javax.swing.JMenuItem jMenuItemAktor2;
    // End of variables declaration//GEN-END:variables
}
